jobs:

- job: 'xonsh_windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      # Uncomment when Python 3.8 is supported
      #Python38:
      #  python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  # Conda Environment
  # Create and activate a Conda environment.
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - script: 'conda create --yes --quiet --name conda-test-$(python.version) -c conda-forge python=$(python.version) snakemake-minimal pytest'
    displayName: 'Conda Environment (conda-forge)'
  - script: |
      call activate conda-test-$(python.version)
      pip install .
      xonsh run-tests.xsh --timeout=10 --junitxml=junit/test-results.%%d.xml
    displayName: 'Tests'
  # Publish build results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
