channels:
  - bioconda
  - r
  - anaconda
  - conda-forge
dependencies:
  - python >=3.3
  - boto
  - moto
  - httpretty
  - filechunkio
  - pyyaml
  - ftputil
  - pysftp
  - requests
  - dropbox
  - appdirs
  - pytools
  - docutils
  - psutil
  - pandas
  - nomkl
  - google-cloud-storage
