version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p miniconda
          export PATH="miniconda/bin:$PATH"
          conda env create --name snakemake --file test-environment.yml
      - run: |
          source activate snakemake
          pip install -e .
      - run: |
          source activate snakemake
          python setup.py nosetests -sx
