version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - snakemake-{{ checksum ".circleci/config.yml" }}-{{ checksum "test-environment.yml" }}-{{ checksum ".circleci/common.sh" }}
      - run:
          name: Setup Conda
          command: |
            echo 'export PATH="/tmp/miniconda/bin:$PATH"' >> $BASH_ENV
            # only install if conda is not yet present
            if type conda > /dev/null; then exit 0; fi
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p /tmp/miniconda
      - run:
          name: Setup singularity
          command: |
            # TODO only install if singularity is not yet present
            # if type singularity > /dev/null; then exit 0; fi
            source .circleci/common.sh
            wget https://github.com/singularityware/singularity/releases/download/$SINGULARITY_VER/singularity-$SINGULARITY_VER.tar.gz
            tar xvf singularity-$SINGULARITY_VER.tar.gz
            cd singularity-$SINGULARITY_VER
            ./configure --prefix=/usr/local --sysconfdir=/etc
            make
            sudo make install
      - run:
          name: Setup test environment
          command: conda env create --name snakemake --file test-environment.yml
      - save_cache:
          key: snakemake-{{ checksum ".circleci/config.yml" }}-{{ checksum "test-environment.yml" }}-{{ checksum ".circleci/common.sh" }}
          paths:
            - /tmp/miniconda
      - run:
          name: Setup Snakemake
          command: |
            source activate snakemake
            pip install -e .
      - run:
          name: Setup iRODS Docker image
          command: |
            docker build -t irods-server tests/test_remote_irods
            docker run -d -p 1247:1247 --name provider irods-server -i run_irods
            sleep 10
            docker exec -u irods provider iput /incoming/infile
            cp -r tests/test_remote_irods/setup-data ~/.irods
      - run:
          name: Run tests
          command: |
            source activate snakemake
            py.test tests/test*.py -v --tb=line
